apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreapi-microservice
  namespace: rockstar
  labels:
    app: coreapi-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coreapi-microservice
  template:
    metadata:
      labels:
        app: coreapi-microservice
    spec:
      containers:
      - name: coreapi-microservice
        image: docker-registry.default.svc:5000/rockstar/coreapi-microservice:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://rockstar:rockstar123@mongodb:27017/rockstardb
        - name: SPRING_DATA_MONGODB_DATABASE
          value: rockstardb
        - name: AUTH0_ISSUER
          value: https://rockstar.auth0.com/
        - name: AUTH0_AUDIENCE
          value: http://api.rock-star.io/v1